<template><PageContainer title="科室信息" desc="支持科室信息的增删查改"><div class="toolbar"><el-input v-model="keyword" placeholder="搜索科室" clearable style="max-width:240px" /><el-button type="primary" @click="openCreate">新增科室</el-button></div><el-table :data="filteredList" border><el-table-column prop="name" label="科室名称" min-width="160" /><el-table-column prop="description" label="科室说明" min-width="220" /><el-table-column prop="location" label="位置" min-width="140" /><el-table-column label="状态" width="100"><template #default="{ row }"><span class="status-tag" :class="row.status === 1 ? 'status-success' : 'status-warning'">{{ row.status === 1 ? '启用' : '停用' }}</span></template></el-table-column><el-table-column label="操作" width="180"><template #default="{ row }"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-dialog v-model="visible" :title="form.id ? '编辑科室' : '新增科室'" width="520px"><el-form :model="form" label-width="80px"><el-form-item label="名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item><el-form-item label="位置"><el-input v-model="form.location" /></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" /></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="submit">保存</el-button></template></el-dialog></PageContainer></template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'; import { adminApi } from '../../api/modules'; import PageContainer from '../../components/PageContainer.vue'; import { confirmAction, successTip } from '../../utils'
const list = ref([]), visible = ref(false), keyword = ref(''); const form = reactive({ id:'', name:'', description:'', location:'', status:1 }); const filteredList = computed(() => list.value.filter(item => !keyword.value || item.name.includes(keyword.value)));
const reset = () => Object.assign(form, { id:'', name:'', description:'', location:'', status:1 });
async function load(){ const res = await adminApi.departments(); list.value = res.data || [] }
function openCreate(){ reset(); visible.value = true }
function openEdit(row){ Object.assign(form, row); visible.value = true }
async function submit(){ if(form.id) await adminApi.updateDepartment(form.id, form); else await adminApi.createDepartment(form); successTip('保存成功'); visible.value = false; load() }
async function remove(row){ await confirmAction(`确认删除科室“${row.name}”吗？`); await adminApi.deleteDepartment(row.id); successTip('删除成功'); load() }
onMounted(load)
</script>